#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- OpenRouter (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

import aiohttp
from dotenv import load_dotenv
from fastapi import HTTPException
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker, ProcessorUnusablePolicy
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.frameworks.rtvi.frames import RTVIUICommandFrame
from pipecat.runner.run import app
from pipecat.runner.types import RunnerArguments
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.llm_service import FunctionCallParams
from pipecat.services.openrouter.llm import OpenRouterLLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.workers.runner import WorkerRunner

from knowledge_loader import load_motion_falcon_knowledge
from lead_capture import LeadCapture, LeadDelivery

load_dotenv(override=True)

SETTINGS_PATH = Path(__file__).with_name(".env")
MAX_LIVE_NOTES = 4
MAX_LIVE_NOTE_CHARS = 160


def _read_env_file() -> dict[str, str]:
    settings: dict[str, str] = {}
    if not SETTINGS_PATH.exists():
        return settings

    for line in SETTINGS_PATH.read_text(encoding="utf-8").splitlines():
        trimmed = line.strip()
        if not trimmed or trimmed.startswith("#") or "=" not in trimmed:
            continue
        key, value = trimmed.split("=", 1)
        settings[key.strip()] = value.strip().strip('"').strip("'")
    return settings


def _get_setting(key: str) -> str:
    return os.getenv(key) or _read_env_file().get(key, "")


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session."""
    logger.info("Starting bot")

    deepgram_key = _get_setting("DEEPGRAM_API_KEY")
    cartesia_key = _get_setting("CARTESIA_API_KEY")
    openrouter_key = _get_setting("OPENROUTER_API_KEY")
    if not deepgram_key or not cartesia_key or not openrouter_key:
        raise HTTPException(
            status_code=500,
            detail="Missing API keys. Please save them from the settings page before connecting.",
        )

    knowledge = await load_motion_falcon_knowledge(
        _get_setting("MOTION_FALCON_KNOWLEDGE_URL"),
        _get_setting("MOTION_FALCON_KNOWLEDGE_TOKEN"),
    )

    stt = DeepgramSTTService(api_key=deepgram_key)

    tts = CartesiaTTSService(
        api_key=cartesia_key,
        settings=CartesiaTTSService.Settings(
            voice=_get_setting("CARTESIA_VOICE_ID") or "86e30c1d-714b-4074-a1f2-1cb6b552fb49",
        ),
    )

    llm = OpenRouterLLMService(
        api_key=openrouter_key,
        settings=OpenRouterLLMService.Settings(
            model=_get_setting("OPENROUTER_MODEL") or "openai/gpt-4o-mini",
            system_instruction=(
                f"{knowledge.system_instruction()}\n\n"
                "After each substantive user turn, call update_live_notes with 1 to 4 concise "
                "pointers capturing the current goals, constraints, decisions, or next steps. "
                "Update the full current set as the conversation evolves. Live Notes are not a "
                "transcript: never include verbatim user or assistant wording, and do not "
                "transcribe every word."
            ),
        ),
    )

    live_notes: list[str] = []

    async def open_lead_capture(params: FunctionCallParams) -> dict[str, str]:
        """Open the consent form after the visitor agrees to share their details."""
        await params.pipeline_worker.queue_frame(RTVIUICommandFrame(command="open-lead-capture"))
        return {"status": "The contact form is open."}

    async def open_scheduling(params: FunctionCallParams) -> dict[str, str]:
        """Open the approved Motion Falcon Calendly booking flow."""
        await params.pipeline_worker.queue_frame(
            RTVIUICommandFrame(
                command="open-scheduling", payload={"url": _get_setting("CALENDLY_URL")}
            )
        )
        return {"status": "The scheduling window is open."}

    async def update_live_notes(params: FunctionCallParams, notes: list[str]) -> dict[str, str]:
        """Replace the concise conversation pointers shown in Live Notes.

        Args:
            notes: One to four short, non-verbatim conversation pointers.
        """
        normalized_notes = []
        for note in notes[:MAX_LIVE_NOTES] if isinstance(notes, list) else []:
            if not isinstance(note, str):
                continue
            normalized_note = " ".join(note.split())[:MAX_LIVE_NOTE_CHARS].strip()
            if normalized_note and normalized_note not in normalized_notes:
                normalized_notes.append(normalized_note)

        live_notes[:] = normalized_notes
        await params.pipeline_worker.queue_frame(
            RTVIUICommandFrame(command="update-live-notes", payload={"notes": normalized_notes})
        )
        return {"status": "Live Notes updated."}

    context = LLMContext(tools=[open_lead_capture, open_scheduling, update_live_notes])
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        processor_unusable_policy=ProcessorUnusablePolicy.END,
    )

    lead_delivery = LeadDelivery(
        hubspot_token=_get_setting("HUBSPOT_PRIVATE_APP_TOKEN"),
        resend_api_key=_get_setting("RESEND_API_KEY"),
        email_from=_get_setting("EMAIL_FROM"),
        calendly_url=_get_setting("CALENDLY_URL"),
    )

    def transcript_for_hubspot() -> str:
        messages = []
        for message in context.get_messages():
            role = message.get("role")
            content = message.get("content")
            if role in {"user", "assistant"} and isinstance(content, str):
                messages.append(f"{role.title()}: {content}")
        return "\n".join(messages)

    async def handle_lead_capture(payload: object) -> None:
        try:
            lead = LeadCapture.from_payload(payload)
            transcript = (
                transcript_for_hubspot()
                if lead.transcript_consent or lead.transcript_email_consent
                else ""
            )
            result = await lead_delivery.deliver(lead, transcript, live_notes)
            if result.failed_destinations:
                failed_destinations = list(result.failed_destinations)
                logger.warning(
                    "Lead delivery incomplete; failed destinations: {}. Reasons: {}",
                    ", ".join(failed_destinations),
                    "; ".join(result.failure_reasons),
                )
                await worker.queue_frame(
                    RTVIUICommandFrame(
                        command="lead-capture-failed",
                        payload={"failedDestinations": failed_destinations},
                    )
                )
                return
            await worker.queue_frame(RTVIUICommandFrame(command="lead-capture-confirmed"))
            await worker.queue_frame(
                RTVIUICommandFrame(
                    command="open-scheduling",
                    payload={
                        "url": _get_setting("CALENDLY_URL"),
                        "name": lead.name,
                        "email": lead.email,
                    },
                )
            )
        except (RuntimeError, ValueError, aiohttp.ClientError, TimeoutError) as error:
            logger.warning(f"Lead capture was not delivered: {error}")
            await worker.queue_frame(RTVIUICommandFrame(command="lead-capture-failed"))

    @worker.rtvi.event_handler("on_ui_message")
    async def on_ui_message(rtvi, message):
        if getattr(message.data, "event", None) == "lead.capture":
            worker.create_task(handle_lead_capture(message.data.payload), "lead_capture")

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        context.add_message(
            {
                "role": "developer",
                "content": "Introduce yourself as Falcon, Motion Falcon's voice assistant. "
                "Offer help with Motion Falcon's creative technology services or a project idea.",
            }
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point compatible with Pipecat runner."""
    webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

    transport = SmallWebRTCTransport(
        webrtc_connection=webrtc_connection,
        params=TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    )

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
