#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- OpenRouter (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from fastapi import HTTPException
from loguru import logger
from pydantic import BaseModel
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker, ProcessorUnusablePolicy
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.run import app
from pipecat.runner.types import RunnerArguments
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.openrouter.llm import OpenRouterLLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.workers.runner import WorkerRunner

load_dotenv(override=True)

ENV_KEYS = {
    "OPENROUTER_API_KEY": "openrouter_api_key",
    "OPENROUTER_MODEL": "openrouter_model",
    "DEEPGRAM_API_KEY": "deepgram_api_key",
    "CARTESIA_API_KEY": "cartesia_api_key",
    "CARTESIA_VOICE_ID": "cartesia_voice_id",
}
SETTINGS_PATH = Path(__file__).with_name(".env")


class SettingsPayload(BaseModel):
    openrouter_api_key: str = ""
    openrouter_model: str = "openai/gpt-4o-mini"
    deepgram_api_key: str = ""
    cartesia_api_key: str = ""
    cartesia_voice_id: str = ""


def _read_env_file() -> dict[str, str]:
    settings: dict[str, str] = {}
    if not SETTINGS_PATH.exists():
        return settings

    for line in SETTINGS_PATH.read_text(encoding="utf-8").splitlines():
        trimmed = line.strip()
        if not trimmed or trimmed.startswith("#") or "=" not in trimmed:
            continue
        key, value = trimmed.split("=", 1)
        settings[key.strip()] = value.strip().strip('"').strip("'")
    return settings


def _write_env_file(changes: dict[str, str]) -> None:
    current = _read_env_file()
    current.update({key: value for key, value in changes.items() if value not in (None, "")})

    lines = ["# Pipecat Quickstart environment variables", "# Generated by the settings page."]
    for key, value in sorted(current.items()):
        lines.append(f"{key}={value}")
    SETTINGS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for key, value in current.items():
        os.environ[key] = value


def _get_setting(key: str) -> str:
    return os.getenv(key) or _read_env_file().get(key, "")


@app.get("/api/settings")
async def get_settings():
    return {
        "openrouter_api_key": _get_setting("OPENROUTER_API_KEY"),
        "openrouter_model": _get_setting("OPENROUTER_MODEL") or "openai/gpt-4o-mini",
        "deepgram_api_key": _get_setting("DEEPGRAM_API_KEY"),
        "cartesia_api_key": _get_setting("CARTESIA_API_KEY"),
        "cartesia_voice_id": _get_setting("CARTESIA_VOICE_ID"),
    }


@app.post("/api/settings")
async def save_settings(payload: SettingsPayload):
    updates = {
        "OPENROUTER_API_KEY": payload.openrouter_api_key,
        "OPENROUTER_MODEL": payload.openrouter_model or "openai/gpt-4o-mini",
        "DEEPGRAM_API_KEY": payload.deepgram_api_key,
        "CARTESIA_API_KEY": payload.cartesia_api_key,
        "CARTESIA_VOICE_ID": payload.cartesia_voice_id,
    }
    _write_env_file(updates)
    return {"ok": True, "settings": await get_settings()}


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session."""
    logger.info("Starting bot")

    deepgram_key = _get_setting("DEEPGRAM_API_KEY")
    cartesia_key = _get_setting("CARTESIA_API_KEY")
    openrouter_key = _get_setting("OPENROUTER_API_KEY")
    if not deepgram_key or not cartesia_key or not openrouter_key:
        raise HTTPException(
            status_code=500,
            detail="Missing API keys. Please save them from the settings page before connecting.",
        )

    stt = DeepgramSTTService(api_key=deepgram_key)

    tts = CartesiaTTSService(
        api_key=cartesia_key,
        settings=CartesiaTTSService.Settings(
            voice=_get_setting("CARTESIA_VOICE_ID") or "86e30c1d-714b-4074-a1f2-1cb6b552fb49",
        ),
    )

    llm = OpenRouterLLMService(
        api_key=openrouter_key,
        settings=OpenRouterLLMService.Settings(
            model=_get_setting("OPENROUTER_MODEL") or "openai/gpt-4o-mini",
            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Respond to what the user said in a creative, helpful, and brief way.",
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        processor_unusable_policy=ProcessorUnusablePolicy.END,
    )

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        context.add_message(
            {"role": "developer", "content": "Please introduce yourself to the user."}
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point compatible with Pipecat runner."""
    webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

    transport = SmallWebRTCTransport(
        webrtc_connection=webrtc_connection,
        params=TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    )

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
